data:
  dataset_path: 'data/'  # default dataset path
  batch_size: 64
  shuffle: True
  num_workers: 4
  class_code: '03001627'  # Class code -> Chairs: 03001627, Tables: 04379243, All: All of data
  split_ratio: 0.8  # Training to testing ratio

training:
  epochs: 100
  learning_rate: 1e-4
  gamma: 0.97  # Hyperparameter for modified BCE
  checkpoint_freq: 20  # Frequency (in epochs) to save model checkpoints
  visualize_freq: 20  # Frequency (in epochs) to visualize network output

model:
  latent_dim: 128
  type: 'VAE'